# Generated by Django 4.2.6 on 2023-10-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сategory_name', models.CharField(max_length=50, verbose_name='наименование категории')),
                ('сategory_description', models.TextField(verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('сategory_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('product_description', models.TextField(verbose_name='описание продукта')),
                ('product_preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='превью')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена за покупку')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
