# Generated by Django 4.2.6 on 2023-10-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default='0', max_length=50, verbose_name='создан в'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.CharField(default='0', max_length=50, verbose_name='создан в'),
        ),
    ]
