# Generated by Django 4.2.6 on 2023-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_created_at_remove_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за покупку'),
        ),
    ]
